apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-bot
  labels:
    app: chat-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-bot
  template:
    metadata:
      labels:
        app: chat-bot
    spec:
      containers:
      - name: chat-bot
        image: trieule0801/chainlit-chatbot:latest
        ports:
        - containerPort: 7860
        # envFrom:
        # - secretRef:
        #     name: chat-bot-secret
