apiVersion: v1
kind: Service
metadata:
  name: chainlit-chatbot-service
spec:
  # type: NodePort   # Or NodePort if LoadBalancer isn't available
  selector:
    app: chainlit-chatbot
  ports:
  - port: 80
    targetPort: 7860
    nodePort: 30786   # Optional, you can let Kubernetes assign a random port choose any available port 30000-32767
